Django-CRUD-master/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from crud import views as crud_views


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(template_name='accounts/logged_in.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/profile', views.UserProfileView.as_view(), name='profile'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('', crud_views.ContactListView.as_view(), name='password_change_done'),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
]

Django-CRUD-master/crud/urls.py
from django.urls import path
from . import views


app_name = 'contact'
urlpatterns = [
    path('contact/create/', views.ContactCreateView.as_view(), name='create'),
    path('contact/update/<int:pk>/', views.ContactUpdateView.as_view(), name='update'),
    path('contact/delete/<int:pk>/', views.ContactDeleteView.as_view(), name='delete'),
    path('', views.ContactListView.as_view(), name='list'),
]

Django-CRUD-master/src/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path(str(os.environ.get('ADMIN_URL', 'admin/')), admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('crud.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django-CRUD-master/accounts/models.py
from django.db import models

# Create your models here.

Django-CRUD-master/crud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



class Contact(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('contact:list')
    
    def get_update_url(self):
        return reverse('contact:update', kwargs={
            'pk': self.id 
        })

    def get_delete_url(self):
        return reverse('contact:delete', kwargs= {
            'pk': self.id
        })

Django-CRUD-master/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Email'
        self.fields['password1'].label = 'New Password'
        self.fields['password2'].label = 'Confirm password'
        

Django-CRUD-master/crud/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'phone_number', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'input-create'})
        self.fields['phone_number'].widget.attrs.update({'class': 'input-create'})
        self.fields['email'].widget.attrs.update({'class': 'input-create'})
        self.fields['phone_number'].label = 'Phone'

Django-CRUD-master/accounts/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.shortcuts import redirect
from .forms import UserCreateForm



class UserCreateView(FormView):
    form_class = UserCreateForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        form.save()
        return redirect('login')


class UserProfileView(TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Profile',
        })
        return context

Django-CRUD-master/crud/views.py
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy

from .models import Contact
from .forms import ContactForm



class ContactCreateView(LoginRequiredMixin, FormView):
    form_class = ContactForm
    template_name = 'crud/contact_form.html'

    def form_valid(self, form):
        contact = form.save(commit=False)
        contact.user = self.request.user
        contact.save()
        return redirect('contact:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Contact Create Form',
            'button': 'Create'
        })
        return context

class ContactUpdateView(LoginRequiredMixin, UpdateView):
    model = Contact
    form_class = ContactForm
    template_name = 'crud/contact_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Contact Update Form',
            'button': 'Update'
        })
        return context


class ContactDeleteView(LoginRequiredMixin, DeleteView):
    model = Contact
    template_name = 'crud/contact_confirm_delete.html'
    success_url = reverse_lazy('contact:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Contact Delete',
        })
        return context


class ContactListView(ListView):
    model = Contact
    template_name = 'crud/contact_list.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Contact.objects.filter(user=self.request.user)
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Contact List'
        })
        return context

Django-CRUD-master/templates/accounts/logged_in.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    
</head>
<body>
    <div style="top: 5%;left: 85%; position: absolute; display: flex;">
        <a href="{% url 'contact:list' %}" id="not-auth">Home</a>
        <a href="{% url 'register' %}" id="not-auth">Sign Up</a>
    </div>
    <div class="block">
        <div class="login-tab">LOG IN</div>
        <form method="post" class="form">
            {% csrf_token %}
            <div class="form-item">
                <label for="username">Username:</label>
                <input type="text" name="username" id="username">
            </div>
            <div class="form-item">
                <label for="password">Password:</label>
                <input type="password" name="password" id="password">
            </div>
            <div class="login">
                <input class="login-text" type="submit" value="Log in">
            </div>
        </form>
    </div>
    <div style="position: absolute; top: 80%; left: 40%; font-size: 16pt;">
        Created by <span style="font-weight: bold;">Kazi MD Khaled Nur</span>
    </div>
</body>
</html>

Django-CRUD-master/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/password_change.css' %}">
{% endblock css %}

{% block body %}
<div class="box">
    <div class="body">
        <div>
            <form method="post">
                {% csrf_token %}
                <div class="form-item">
                    {{ form.old_password.errors }}
                    <label for="old_password">Old Password:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" name="old_password" id="old_password">
                </div>
                <div class="form-item">
                    {{ form.new_password1.errors }}
                    <label for="new_password1">New Password:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" name="new_password1" id="new_password1">
                </div>
                <div class="form-item">
                    {{ form.new_password2.errors }}
                    <label for="new_password2">Confirm Password:&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" name="new_password2" id="new_password2">
                </div>
                <div class="change_password">
                    <input class="change_password-text" type="submit" value="Change Password">
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

Django-CRUD-master/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock css %}

{% block body %}
<div class="box">
    <div class="title">
        Profile
    </div>
    <div class="body">
        <div class="user-detail-list">
            <div class="flex user-detail">
                <div class="username">Username:</div>
                <div>{{ request.user.username }}</div>
            </div>
            <div class="flex user-detail">
                <div class="email">Email:</div>
                <div>{{ request.user.email }}</div>
            </div>
        </div>
        <div class="change-password">
            <a href="{% url 'password_change' %}" class="change-password-text">Change Password</a>
        </div>
    </div>
</div>

{% endblock body %}

Django-CRUD-master/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>
<body>
    <div style="top: 5%;left: 85%; position: absolute; display: flex;">
        <a href="{% url 'contact:list' %}" id="not-auth">Home</a>
        <a href="{% url 'login' %}" id="not-auth">Log In</a>
    </div>
    <div class="block">
        <div class="signup-tab">SIGN UP FORM</div>
        <form method="post" class="form">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-item">
                {{ field.errors }}
                {{ field.label_tag }} 
                {{ field }}
            </div>
            {% endfor %}
            <div class="signup">
                <input class="signup-text" type="submit" value="Sign up">
            </div>
        </form>
    </div>
    <div style="position: absolute; top: 80%; left: 40%; font-size: 16pt;">
        Created by <span style="font-weight: bold;">Kazi MD Khaled Nur</span>
    </div>
</body>
</html>

Django-CRUD-master/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %}
    {% endblock css %}
</head>
<body>

{% if request.user.is_authenticated %}

{% block create %}
{% endblock %}

{% else %}
<div class="absolute" style="left: 85%">
    <a href="{% url 'register' %}" id="not-auth">Sign Up</a>
    <a href="{% url 'login' %}" id="not-auth">Log In</a>
</div>
{% endif %}

{% block body %}
{% endblock body %}

<div style="padding: 2rem; text-align: center; font-size: 16pt;">
    Created by <span style="font-weight: bold;">Kazi MD Khaled Nur</span>
</div>

</body>
</html>

Django-CRUD-master/templates/crud/contact_confirm_delete.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/contact_confirm_delete.css' %}">
{% endblock css %}


{% block create %}
<div class="absolute" style="left: 3.5%; top: 4%">
    <a href="{% url 'contact:list' %}" class="username">@{{ request.user.username }}</a>
</div>
<div class="absolute" style="left: 85%; top: 5%">
    <a href="{% url 'contact:list' %}" id="auth"style="padding-top: 2px;">Home</a>
    <a href="{% url 'logout' %}" id="auth" style="padding-top: 2px;">
        Log Out
    </a>
</div>
{% endblock create %}


{% block body %}
<div class="alert-message">
    <div class="alert-message-text">
        Are you want to delete it?
    </div>
    <div>
        <form class="delete-form" method="post">
            {% csrf_token %}
            <input id="delete-btn" type="submit" value="Delete">
            <a id="cancel-btn" href="{% url 'contact:list' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock body %}

Django-CRUD-master/templates/crud/contact_form.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/contact_form.css' %}">
{% endblock css %}

{% block create %}
<div class="absolute" style="left: 3.5%;">
    <a href="{% url 'contact:list' %}" class="username">@{{ request.user.username }}</a>
</div>
<div class="absolute" style="left: 85%">
    <a href="{% url 'contact:list' %}" id="auth"style="padding-top: 2px;">Home</a>
    <a href="{% url 'logout' %}" id="auth" style="padding-top: 2px;">
        Log Out
    </a>
</div>
{% endblock create %}

{% block body %}
    
<div class="title">
    {{ title }}
</div>

<div class="box">
    <form class="form-create" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-item">
            {{ field.errors }}
            {{ field.label_tag }} 
            {{ field }}
        </div>
        {% endfor %}
        <div>
            <input class="submit" type="submit" value="{{ button }}">
        </div>
    </form>
</div>

{% endblock body %}

Django-CRUD-master/templates/crud/contact_list.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/contact_list.css' %}">
{% endblock css %}

{% block create %}
<div class="absolute" style="left: 3.5%;">
    <a href="{% url 'profile' %}" class="username">@{{ request.user.username }}</a>
</div>
<div class="absolute" style="left: 82%">
    <a id="add-contact" href="{% url 'contact:create' %}">
        <div class="button-svg">
            <svg xmlns="http://www.w3.org/2000/svg" height=25 width=25 viewBox="0 0 24 24" fill="currentColor">
                <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" color="white"/>
            </svg>
        </div>
        <div class="button-text">
            Add Contact
        </div>
    </a>
    <a id="auth" href="{% url 'logout' %}">
        Log Out
    </a>
</div>
{% endblock create %}


{% block body %}

<div class="title">
    Contact List
</div>
<div class="table" >
    <table>
        <thead>
            <tr id="table-header-list">
                <th class="table-header" id="name">Name</th>
                <th class="table-header" id="phone">Phone</th>
                <th class="table-header" id="email">Email</th>
                <th class="table-header" id="delete"></th>
            </tr>
        </thead>
        {% if request.user.is_authenticated %}
        {% if contact_list %}
        <tbody>
            {%for contact in contact_list %}
            <tr>
                <td><a href="{{ contact.get_update_url }}" style="color: black;">{{ contact.name }}</a></td>
                <td><a href="{{ contact.get_update_url }}" style="color: black;">{{ contact.phone_number }}</a></td>
                <td><a href="{{ contact.get_update_url }}" style="color: black;">{{ contact.email }}</a></td>
                <td>
                    <a href="{{ contact.get_delete_url }}">
                        <svg xmlns="http://www.w3.org/2000/svg" height=20 width=20 fill="none" viewBox="0 0 24 24" stroke="currentColor" class="delete-icon">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td class="contact-message" colspan="4">You have no Contact.</td>
            </tr>
        </tbody>
        {% endif%}
        {% else %}
        <tbody>
            <tr>
                <td class="contact-message" colspan="4">You have to log in to see your Contact list.</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
</div>

{% endblock body %}